lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(APP_SECRET)%'
    token_ttl:        3600
